<a href="https://colab.research.google.com/github/nandan758/machine-Learing-lab-CS-604PC/blob/main/MLprog_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Create a simple dataset
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Display the first few rows
print(df.head())

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [11]:
 import pandas as pd
 df = pd.DataFrame(
       {
            "Name": [
                "Braund, Mr. Owen Harris",
               "Allen, Mr. William Henry",
               "Bonnell, Miss. Elizabeth",
           ],
           "Age": [22, 35, 58],
           "gender": ["male", "male", "female"],
        }
    )


 df

                       Name  Age  gender
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [12]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [13]:
df['Age'].max()

58

In [20]:
#some basic statistics of the numerical data of my data table
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000